// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CocktailCardController from "./cocktail_card_controller"
application.register("cocktail-card", CocktailCardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SubmitOnEnterController from "./submit_on_enter_controller"
application.register("submit-on-enter", SubmitOnEnterController)
